src-git helloworld https://github.com/fw876/helloworld
src-git passwall_packages https://github.com/Openwrt-Passwall/openwrt-passwall-packages.git;main
src-git passwall2 https://github.com/Openwrt-Passwall/openwrt-passwall2.git;main
src-git istore https://github.com/linkease/istore;main
